export type EnergyKey = "red" | "yellow" | "green" | "blue";
export type AvailKey = "now" | "soon" | "allocated";

export interface Person {
  id: number;
  name: string;
  initials: string;
  role: string;
  location: string;
  primary: EnergyKey;
  secondary: EnergyKey;
  scores: { red: number; yellow: number; green: number; blue: number };
  utilisation: number;
  available: AvailKey;
  clients: number;
  revenue: string;
  dayRate: number;
  bio: string;
  capabilities: string[];
  achievements: string[];
  bestTrait: string;
  vice: string;
  wheelPosition: string;
  drivers: string[];
  detractors: string[];
  howToSpeak: string;
  howToEmail: string;
}

export const energy: Record<
  EnergyKey,
  { color: string; bg: string; text: string; border: string; label: string }
> = {
  red:    { color: "#E8402A", bg: "#FDF0EE", text: "#9B2A1A", border: "#FCCDC6", label: "Drive" },
  yellow: { color: "#F5A623", bg: "#FFFBF2", text: "#8B5A00", border: "#FAD98A", label: "Spark" },
  green:  { color: "#2E8B57", bg: "#EEF7F2", text: "#1A5C38", border: "#9ED4B8", label: "Steady" },
  blue:   { color: "#1E6FA5", bg: "#EEF4FB", text: "#124A6E", border: "#8DC2E8", label: "Lens" },
};

export const availability: Record<
  AvailKey,
  { color: string; bg: string; text: string; border: string; label: string }
> = {
  now:       { color: "#2E8B57", bg: "#EEF7F2", text: "#1A5C38", border: "#9ED4B8", label: "Available now" },
  soon:      { color: "#F5A623", bg: "#FFFBF2", text: "#8B5A00", border: "#FAD98A", label: "Available soon" },
  allocated: { color: "#E8402A", bg: "#FDF0EE", text: "#9B2A1A", border: "#FCCDC6", label: "Allocated" },
};

export function utilTone(u: number): { color: string; label: string } {
  if (u >= 80) return { color: "#2E8B57", label: "On target" };
  if (u >= 65) return { color: "#F5A623", label: "Below target" };
  return { color: "#E8402A", label: "At risk" };
}

export const people: Person[] = [
  {
    id: 1,
    name: "Linnea Sjöberg",
    initials: "LS",
    role: "Engagement Director",
    location: "Stockholm",
    primary: "red",
    secondary: "yellow",
    scores: { red: 86, yellow: 71, green: 32, blue: 44 },
    utilisation: 92,
    available: "allocated",
    clients: 6,
    revenue: "€1.4M",
    dayRate: 3500,
    bio: "Senior delivery lead with 14 years across financial services and retail. Known for landing big-ticket pitches and turning around stalled engagements without burning the team out.",
    capabilities: ["Engagement leadership", "Pitch & sales", "Digital strategy", "Stakeholder management"],
    achievements: [
      "Closed €4.2M Nordea omnichannel programme — largest Nordic win of 2025.",
      "Stabilised the H&M loyalty rebuild after a six-month delivery slip.",
      "Mentor to four senior consultants now leading their own engagements.",
    ],
    bestTrait: "Cuts through noise — makes the hard call when no one else will.",
    vice: "Can run past people. Watch for steamrolling in early-stage workshops.",
    wheelPosition: "Catalysing Driver",
    drivers: ["Winning competitive pitches", "Visible commercial impact", "Pace and momentum", "High-trust autonomy"],
    detractors: ["Endless alignment meetings", "Vague briefs", "Micro-management", "Death by committee"],
    howToSpeak: "Be direct and lead with the headline. Linnea wants the bottom line in the first sentence — context comes after. Skip the small talk and bring decisions, not options to admire.",
    howToEmail: "Short paragraphs. Bold the asks. One decision per email. If you need a yes by Thursday, say so in the subject line — she scans first and reads second.",
  },
  {
    id: 2,
    name: "Mathias Lund",
    initials: "ML",
    role: "Principal Tech Lead",
    location: "Copenhagen",
    primary: "blue",
    secondary: "green",
    scores: { red: 28, yellow: 24, green: 64, blue: 91 },
    utilisation: 78,
    available: "soon",
    clients: 3,
    revenue: "€820k",
    dayRate: 2800,
    bio: "Backend architect specialising in event-driven systems. The person we send in when an engagement is technically off the rails and needs a calm hand to redesign without drama.",
    capabilities: ["Distributed systems", "Event sourcing", "AWS architecture", "Technical due diligence"],
    achievements: [
      "Re-architected Maersk shipment events platform — 99.99% uptime since go-live.",
      "Authored the Valtech Nordic event-driven reference architecture.",
      "Speaker at GOTO Copenhagen 2025 on graceful degradation.",
    ],
    bestTrait: "Sees the second-order failure before anyone else does.",
    vice: "Will over-engineer if left unsupervised on a quiet sprint.",
    wheelPosition: "Building Analyst",
    drivers: ["Hard technical problems", "Quiet focus time", "Written specs", "Clean abstractions"],
    detractors: ["Hand-wavy requirements", "Pressure to ship without review", "Open-plan noise", "Status theatre"],
    howToSpeak: "Bring the data. Mathias wants the constraint, the trade-off, and the failure mode. Speak slower than you think you should and leave space for him to think before he answers.",
    howToEmail: "Threaded, structured, with headings if it's long. Send the doc 24 hours before the meeting. He'll come back with the four questions that actually matter.",
  },
  {
    id: 3,
    name: "Pernille Andersen",
    initials: "PA",
    role: "UX Director",
    location: "Copenhagen",
    primary: "green",
    secondary: "yellow",
    scores: { red: 22, yellow: 67, green: 88, blue: 41 },
    utilisation: 84,
    available: "allocated",
    clients: 4,
    revenue: "€690k",
    dayRate: 3500,
    bio: "User research and service design lead. Builds psychologically safe teams where junior designers do their best work. Clients ask for her by name three years after engagements end.",
    capabilities: ["Service design", "Qualitative research", "Workshop facilitation", "Team coaching"],
    achievements: [
      "Led the Danske Bank onboarding redesign — NPS up 31 points.",
      "Founded the Nordic UX guild; 40+ members across four offices.",
      "Promoted three designers to senior in the last 18 months.",
    ],
    bestTrait: "Holds the room — gets the quietest voice talking by minute ten.",
    vice: "Avoids hard conversations longer than she should.",
    wheelPosition: "Caring Anchor",
    drivers: ["Healthy team dynamics", "Long-term client relationships", "Mentoring juniors", "Real user contact"],
    detractors: ["Conflict left to fester", "Last-minute scope changes", "Cynicism", "Being asked to choose between people"],
    howToSpeak: "Slow down and ask about the team before the work. Pernille reads tone first, content second. If something's hard, name it gently — she'll meet you there.",
    howToEmail: "Warm opener, clear ask, no jargon. Acknowledge the human side of any change before the timeline. She'll reply thoughtfully, not quickly.",
  },
  {
    id: 4,
    name: "Aksel Berg",
    initials: "AB",
    role: "Strategy Consultant",
    location: "Oslo",
    primary: "yellow",
    secondary: "red",
    scores: { red: 64, yellow: 89, green: 41, blue: 36 },
    utilisation: 71,
    available: "soon",
    clients: 5,
    revenue: "€510k",
    dayRate: 2000,
    bio: "Strategy and innovation consultant. The face in the room at C-suite workshops — turns abstract ambition into a roadmap clients can actually start on Monday.",
    capabilities: ["Innovation strategy", "C-suite facilitation", "Storytelling", "New venture design"],
    achievements: [
      "Designed Equinor's customer innovation lab from a blank page.",
      "Top-rated facilitator on Valtech Nordic's exec leadership programme 2024 and 2025.",
      "Hosted four Innovation Mondays bringing in 60+ client leaders.",
    ],
    bestTrait: "Gets a sceptical exec team excited and aligned in one workshop.",
    vice: "Loves the kickoff, drifts on the long middle. Pair with a strong delivery lead.",
    wheelPosition: "Connecting Catalyst",
    drivers: ["New ideas", "Visible audiences", "Variety", "Big-picture problems"],
    detractors: ["Repetitive admin", "Solo deep work for days", "Cynics in the room", "Tight process boxes"],
    howToSpeak: "Bring energy. Aksel matches the room — if you're flat, the workshop will be flat. Use stories, not bullet points, and let him riff before you converge.",
    howToEmail: "Short, warm, with a hook in line one. Skip long preambles. He replies on the move so keep the ask scannable on a phone screen.",
  },
  {
    id: 5,
    name: "Henna Mäkinen",
    initials: "HM",
    role: "Senior Data Scientist",
    location: "Helsinki",
    primary: "blue",
    secondary: "red",
    scores: { red: 58, yellow: 31, green: 39, blue: 88 },
    utilisation: 88,
    available: "allocated",
    clients: 2,
    revenue: "€420k",
    dayRate: 2000,
    bio: "Applied ML lead with a stats PhD. Builds production models that survive contact with real data. Direct, occasionally blunt, deeply respected by engineering.",
    capabilities: ["Applied ML", "MLOps", "Causal inference", "Forecasting"],
    achievements: [
      "Shipped Kesko's demand forecasting model — 14% inventory reduction in pilot stores.",
      "Built the Nordic MLOps reference stack now used on six engagements.",
      "Published two papers on time-series uncertainty in retail.",
    ],
    bestTrait: "Will tell you when the model isn't ready, even when the client doesn't want to hear it.",
    vice: "Low patience for vague business questions — coach her to translate, don't shield her.",
    wheelPosition: "Refining Analyst",
    drivers: ["Clean data", "Quantifiable problems", "Intellectual honesty", "Fast iteration cycles"],
    detractors: ["Vanity metrics", "Stakeholders who won't pick a target", "Theatre over substance", "Vague success criteria"],
    howToSpeak: "Lead with the question and the metric. Henna wants to know what decision the work informs. Don't soften — she reads softening as evasion.",
    howToEmail: "Numbered points. State the hypothesis. Attach the notebook. She'll respond with sharper questions than you sent.",
  },
  {
    id: 6,
    name: "Erik Holm",
    initials: "EH",
    role: "Solutions Architect",
    location: "Stockholm",
    primary: "blue",
    secondary: "green",
    scores: { red: 26, yellow: 38, green: 71, blue: 84 },
    utilisation: 67,
    available: "soon",
    clients: 3,
    revenue: "€540k",
    dayRate: 2000,
    bio: "Cross-functional architect who bridges product, engineering and ops. Calm in escalations, thorough in writeups, the person clients trust when stakes are high.",
    capabilities: ["Enterprise architecture", "API design", "Cloud migration", "Technical writing"],
    achievements: [
      "Migrated SAS Group's customer platform off mainframe with zero downtime.",
      "Authored the Valtech Nordic cloud migration playbook.",
      "Trained 20+ engineers in solution-architecture fundamentals.",
    ],
    bestTrait: "Brings order to chaos without making anyone feel small.",
    vice: "Can overthink first drafts. Time-box his exploratory phases.",
    wheelPosition: "Building Analyst",
    drivers: ["Well-scoped problems", "Cross-team collaboration", "Documentation", "Mentoring engineers"],
    detractors: ["Crisis-mode escalations", "Politics", "Shipping before review", "Ambiguous ownership"],
    howToSpeak: "Be patient and precise. Erik thinks before he answers — silence isn't disagreement. Give him the constraints and the success criteria upfront.",
    howToEmail: "Structured, with context first, then the ask. He'll often reply with a diagram or a doc rather than prose — that's a good sign.",
  },
  {
    id: 7,
    name: "Saga Lindqvist",
    initials: "SL",
    role: "Senior Product Designer",
    location: "Stockholm",
    primary: "yellow",
    secondary: "green",
    scores: { red: 33, yellow: 86, green: 72, blue: 38 },
    utilisation: 81,
    available: "allocated",
    clients: 4,
    revenue: "€460k",
    dayRate: 2000,
    bio: "Product designer with a service-design heart. Pairs effortlessly with engineering, runs lightweight workshops that move decisions forward instead of generating Post-its.",
    capabilities: ["Product design", "Design systems", "Prototyping", "Workshop facilitation"],
    achievements: [
      "Led the Telia self-service redesign — 22% drop in support tickets.",
      "Built the Valtech Nordic design-system kit now used by 30+ designers.",
      "Hosted the Stockholm design meetup three years running.",
    ],
    bestTrait: "Makes complex flows feel inevitable — clients ask why it wasn't always like this.",
    vice: "Sometimes resists pushback she'd benefit from. Frame critique as collaboration.",
    wheelPosition: "Connecting Carer",
    drivers: ["Cross-discipline collaboration", "Real users in the room", "Craft pride", "A clear product vision"],
    detractors: ["HiPPO decisions", "Design by committee", "Endless rounds without users", "Politics dressed as feedback"],
    howToSpeak: "Be curious, not corrective. Saga responds to 'what if we tried X?' more than 'we need X'. Bring her into the framing, not just the build.",
    howToEmail: "Conversational, with a Figma link and a single clear question. Long briefs lose her — anchor the email to one decision.",
  },
  {
    id: 8,
    name: "Tobias Krogh",
    initials: "TK",
    role: "Delivery Lead",
    location: "Copenhagen",
    primary: "green",
    secondary: "blue",
    scores: { red: 31, yellow: 42, green: 87, blue: 69 },
    utilisation: 86,
    available: "allocated",
    clients: 2,
    revenue: "€780k",
    dayRate: 2800,
    bio: "Programme manager who keeps engagements healthy. Quietly unblocks two things before standup that no one knew were stuck. Loved by both clients and engineers.",
    capabilities: ["Programme management", "Agile delivery", "Risk management", "Client governance"],
    achievements: [
      "Recovered the Carlsberg loyalty programme on the original launch date.",
      "Coached two team leads through their first major client escalation.",
      "Built the delivery health-check now used across every Nordic engagement.",
    ],
    bestTrait: "Stays calm in a storm — the team trusts him because he never panics.",
    vice: "Will absorb pressure himself rather than escalate. Check in regularly.",
    wheelPosition: "Building Anchor",
    drivers: ["Team wellbeing", "Predictable cadence", "Clear roles", "Long-term partnerships"],
    detractors: ["Last-minute scope swings", "Heroics culture", "Skipped retros", "Manufactured urgency"],
    howToSpeak: "Be steady. Tobias reads tone — if you're agitated, he'll first calm the room and then ask what's actually wrong. Bring facts, not vibes.",
    howToEmail: "Plain language, clear status, no surprises. Flag risks early and explicitly. He'll handle the rest with a calmer message to the client than you would have sent.",
  },
  {
    id: 9,
    name: "Ida Sørensen",
    initials: "IS",
    role: "Senior Frontend Engineer",
    location: "Oslo",
    primary: "yellow",
    secondary: "blue",
    scores: { red: 34, yellow: 84, green: 47, blue: 71 },
    utilisation: 74,
    available: "soon",
    clients: 3,
    revenue: "€330k",
    dayRate: 2000,
    bio: "React specialist who pairs design sensibility with type-system rigour. Brings energy into the engineering team — the rare frontend clients want in the workshop.",
    capabilities: ["React & Next.js", "TypeScript", "Accessibility", "Design-engineering bridge"],
    achievements: [
      "Led the Storebrand member portal rebuild — Lighthouse 98 on launch.",
      "Authored the Nordic frontend accessibility playbook.",
      "Maintains three popular internal Valtech Nordic component libraries.",
    ],
    bestTrait: "Translates fluently between design and engineering — no information lost.",
    vice: "Can take critique of her code personally. Frame as 'how do we make it better' not 'this is wrong'.",
    wheelPosition: "Connector",
    drivers: ["Craft and polish", "Working with designers", "Trying new tools", "Visible user impact"],
    detractors: ["Vague requirements", "Style-over-substance reviews", "Being siloed from product", "Slow CI"],
    howToSpeak: "Bring warmth and curiosity. Ida wants to feel like a partner, not a ticket-taker. Ask what she'd do differently if she owned the problem outright.",
    howToEmail: "Friendly, with a Loom or a screenshot. Long text emails will get a short reply — better to jump on a call when nuance matters.",
  },
  {
    id: 10,
    name: "Niko Virtanen",
    initials: "NV",
    role: "Senior Backend Engineer",
    location: "Helsinki",
    primary: "blue",
    secondary: "red",
    scores: { red: 61, yellow: 28, green: 36, blue: 87 },
    utilisation: 59,
    available: "now",
    clients: 2,
    revenue: "€280k",
    dayRate: 2000,
    bio: "Backend engineer with a security mindset. Quietly precise, asks the question that exposes the shaky assumption. Coming off a long engagement and ready for the next hard problem.",
    capabilities: ["Go & Rust", "API security", "Postgres performance", "Threat modelling"],
    achievements: [
      "Closed five critical CVEs in OP Financial's customer API in his first quarter.",
      "Designed the auth service used across three Valtech Nordic engagements.",
      "Holds OSCP — runs our internal security book club.",
    ],
    bestTrait: "Spots the security or performance hole that every other reviewer missed.",
    vice: "Can be terse in PR reviews. Pair him with a softer reviewer on junior code.",
    wheelPosition: "Refining Analyst",
    drivers: ["Hard problems", "Security and correctness", "Quiet focus", "Honest code review"],
    detractors: ["Performance theatre", "Bureaucratic process", "Vague success criteria", "Drive-by feedback"],
    howToSpeak: "Be specific and brief. Niko respects people who've done their homework. Don't bring problems you haven't tried to solve yourself first.",
    howToEmail: "Bullet points and code blocks. State the threat model or the constraint. He'll engage deeply when the question is sharp.",
  },
  {
    id: 11,
    name: "Astrid Falk",
    initials: "AF",
    role: "Client Partner",
    location: "Stockholm",
    primary: "red",
    secondary: "yellow",
    scores: { red: 82, yellow: 78, green: 36, blue: 41 },
    utilisation: 64,
    available: "now",
    clients: 7,
    revenue: "€1.1M",
    dayRate: 3500,
    bio: "Senior client partner owning the top three Nordic accounts. Reads a room in seconds, negotiates hard, leaves the relationship stronger than she found it.",
    capabilities: ["Account leadership", "Negotiation", "Executive coaching", "Pipeline building"],
    achievements: [
      "Renewed the Nordea master agreement at +18% on prior commercials.",
      "Built the Volvo Cars relationship from a single statement of work into a programme.",
      "Coached two seniors into client-partner roles.",
    ],
    bestTrait: "Walks into a tough client meeting and walks out with a bigger relationship.",
    vice: "Can over-commit the delivery team to land the deal. Bring her into capacity calls early.",
    wheelPosition: "Catalysing Driver",
    drivers: ["High-stakes negotiations", "Executive relationships", "Visible wins", "Pace"],
    detractors: ["Sluggish internal process", "Delivery surprises", "Indecisive stakeholders", "Sandbagged targets"],
    howToSpeak: "Be confident and concise. Astrid respects people who own a position. Bring options with a clear recommendation, not a menu.",
    howToEmail: "Two paragraphs max. Lead with the commercial impact. She'll move fast — make sure you can match the pace.",
  },
  {
    id: 12,
    name: "Magnus Dahl",
    initials: "MD",
    role: "Engineering Manager",
    location: "Oslo",
    primary: "red",
    secondary: "blue",
    scores: { red: 79, yellow: 38, green: 42, blue: 74 },
    utilisation: 83,
    available: "allocated",
    clients: 3,
    revenue: "€620k",
    dayRate: 2800,
    bio: "Engineering manager with a deep technical bench. Sets a high bar, runs tight engagements, and grows engineers fast. The person clients ask for when timelines look impossible.",
    capabilities: ["Engineering management", "Technical strategy", "Hiring", "Performance coaching"],
    achievements: [
      "Built the Equinor data-platform team from 2 to 14 in 18 months.",
      "Led the rescue of the Posten Norge logistics rebuild on the original deadline.",
      "Coached six engineers into senior in the last two years.",
    ],
    bestTrait: "Drives outcomes without dropping people. Engineers stay because of him.",
    vice: "High standards can read as cold. Pair with a warmer comms lead for sensitive clients.",
    wheelPosition: "Refining Driver",
    drivers: ["High-performing teams", "Clear ownership", "Engineering rigour", "Stretch goals"],
    detractors: ["Process without purpose", "Tolerated underperformance", "Slow decisions", "Politics"],
    howToSpeak: "Be direct and bring a position. Magnus will probe — that's not opposition, that's interest. Don't hedge; he reads hedging as weakness.",
    howToEmail: "Short, structured, with a recommendation. Numbered actions get done. Vague threads get archived.",
  },
];
