import type { Job, Candidate } from "./types";

export const seedJobs: Job[] = [
  {
    id: 1,
    internalTitle: "Senior Frontend Engineer — Storebrand portal",
    externalTitle: "Senior Frontend Engineer (React/Next.js)",
    department: "Engineering",
    location: "Stockholm",
    market: "Stockholm",
    status: "active",
    recruiterId: 2,
    hiringManagerId: 12,
    tags: ["React", "TypeScript", "Senior"],
    createdDate: "2026-05-02",
    applicationCount: 14,
    requiredEnergy: "energizer",
    teamId: null,
  },
  {
    id: 2,
    internalTitle: "Engagement Director — Nordic growth",
    externalTitle: "Engagement Director",
    department: "Consulting",
    location: "Oslo",
    market: "Oslo",
    status: "active",
    recruiterId: 2,
    hiringManagerId: 1,
    tags: ["Leadership", "Client partner"],
    createdDate: "2026-04-18",
    applicationCount: 7,
    requiredEnergy: "driver",
    teamId: null,
  },
  {
    id: 3,
    internalTitle: "Senior Product Designer — Copenhagen team",
    externalTitle: "Senior Product Designer",
    department: "Design",
    location: "Copenhagen",
    market: "Copenhagen",
    status: "active",
    recruiterId: 2,
    hiringManagerId: 3,
    tags: ["Product design", "Senior", "Design systems"],
    createdDate: "2026-05-12",
    applicationCount: 21,
    requiredEnergy: "energizer",
    teamId: null,
  },
  {
    id: 4,
    internalTitle: "Data Scientist — Helsinki",
    externalTitle: "Data Scientist (Applied ML)",
    department: "Data",
    location: "Helsinki",
    market: "Helsinki",
    status: "active",
    recruiterId: 2,
    hiringManagerId: 5,
    tags: ["ML", "Python", "Mid-senior"],
    createdDate: "2026-04-30",
    applicationCount: 9,
    requiredEnergy: "analyst",
    teamId: null,
  },
  {
    id: 5,
    internalTitle: "Solutions Architect — Stockholm cloud team",
    externalTitle: "Solutions Architect",
    department: "Engineering",
    location: "Stockholm",
    market: "Stockholm",
    status: "paused",
    recruiterId: 2,
    hiringManagerId: 6,
    tags: ["Architecture", "AWS", "Senior"],
    createdDate: "2026-03-14",
    applicationCount: 11,
    requiredEnergy: "analyst",
    teamId: null,
  },
  {
    id: 6,
    internalTitle: "Delivery Lead — Copenhagen account team",
    externalTitle: "Delivery Lead",
    department: "Consulting",
    location: "Copenhagen",
    market: "Copenhagen",
    status: "draft",
    recruiterId: 2,
    hiringManagerId: 8,
    tags: ["Delivery", "Lead"],
    createdDate: "2026-05-20",
    applicationCount: 0,
    requiredEnergy: "supporter",
    teamId: null,
  },
  {
    id: 7,
    internalTitle: "Backend Engineer — Maersk shipment team",
    externalTitle: "Senior Backend Engineer (Go)",
    department: "Engineering",
    location: "Copenhagen",
    market: "Copenhagen",
    status: "closed",
    recruiterId: 2,
    hiringManagerId: 2,
    tags: ["Go", "Distributed systems"],
    createdDate: "2026-02-08",
    applicationCount: 32,
    requiredEnergy: "analyst",
    teamId: null,
  },
];

export const seedCandidates: Candidate[] = [
  {
    id: 101,
    jobId: 1,
    name: "Elin Norberg",
    email: "elin.norberg@example.com",
    location: "Stockholm",
    linkedIn: "linkedin.com/in/elinnorberg",
    currentStage: "manager-interview",
    rating: 4,
    tags: ["Strong portfolio", "Available June"],
    isInternal: false,
    pulseProfile: {
      primary: "energizer",
      secondary: "analyst",
      scores: { driver: 38, energizer: 81, supporter: 49, analyst: 72 },
      wheelPosition: "Energizer",
      confidence: 78,
    },
    teamFitScore: 84,
    appliedDate: "2026-05-08",
    source: "linkedin",
  },
  {
    id: 102,
    jobId: 1,
    name: "Theo Lindholm",
    email: "theo@example.com",
    location: "Gothenburg",
    linkedIn: "linkedin.com/in/theolindholm",
    currentStage: "phone-screening",
    rating: 3,
    tags: ["Remote"],
    isInternal: false,
    pulseProfile: {
      primary: "analyst",
      secondary: "supporter",
      scores: { driver: 31, energizer: 44, supporter: 70, analyst: 82 },
      wheelPosition: "Supportive Analyst",
      confidence: 64,
    },
    teamFitScore: 71,
    appliedDate: "2026-05-12",
    source: "direct",
  },
  {
    id: 103,
    jobId: 1,
    name: "Marie Eklund",
    email: "marie@example.com",
    location: "Stockholm",
    linkedIn: null,
    currentStage: "inbox",
    rating: 0,
    tags: [],
    isInternal: false,
    pulseProfile: null,
    teamFitScore: null,
    appliedDate: "2026-05-22",
    source: "agency",
  },
  {
    id: 104,
    jobId: 1,
    name: "Ida Sørensen",
    email: "ida.sorensen@valtech.com",
    location: "Oslo",
    linkedIn: "linkedin.com/in/idasorensen",
    currentStage: "reviewing",
    rating: 5,
    tags: ["Internal candidate"],
    isInternal: true,
    pulseProfile: {
      primary: "energizer",
      secondary: "analyst",
      scores: { driver: 34, energizer: 84, supporter: 47, analyst: 71 },
      wheelPosition: "Energizer",
      confidence: 92,
    },
    teamFitScore: 88,
    appliedDate: "2026-05-19",
    source: "internal",
  },
  {
    id: 105,
    jobId: 1,
    name: "Olof Westin",
    email: "olof@example.com",
    location: "Stockholm",
    linkedIn: "linkedin.com/in/olofwestin",
    currentStage: "hr-interview",
    rating: 4,
    tags: ["Reference checked"],
    isInternal: false,
    pulseProfile: {
      primary: "energizer",
      secondary: "supporter",
      scores: { driver: 41, energizer: 78, supporter: 64, analyst: 52 },
      wheelPosition: "Supportive Energizer",
      confidence: 71,
    },
    teamFitScore: 76,
    appliedDate: "2026-04-30",
    source: "referral",
  },
  {
    id: 106,
    jobId: 2,
    name: "Lars Hauge",
    email: "lars.hauge@example.com",
    location: "Oslo",
    linkedIn: "linkedin.com/in/larshauge",
    currentStage: "manager-interview",
    rating: 5,
    tags: ["Top of pipeline"],
    isInternal: false,
    pulseProfile: {
      primary: "driver",
      secondary: "energizer",
      scores: { driver: 88, energizer: 72, supporter: 30, analyst: 41 },
      wheelPosition: "Energizing Driver",
      confidence: 84,
    },
    teamFitScore: 81,
    appliedDate: "2026-05-04",
    source: "linkedin",
  },
  {
    id: 107,
    jobId: 2,
    name: "Anna Karoline Sand",
    email: "anna@example.com",
    location: "Oslo",
    linkedIn: "linkedin.com/in/akssand",
    currentStage: "offer",
    rating: 5,
    tags: ["Offer extended"],
    isInternal: false,
    pulseProfile: {
      primary: "driver",
      secondary: "analyst",
      scores: { driver: 80, energizer: 51, supporter: 38, analyst: 69 },
      wheelPosition: "Analytical Driver",
      confidence: 88,
    },
    teamFitScore: 79,
    appliedDate: "2026-04-12",
    source: "referral",
  },
  {
    id: 108,
    jobId: 2,
    name: "Per Wiborg",
    email: "per@example.com",
    location: "Oslo",
    linkedIn: "linkedin.com/in/perwiborg",
    currentStage: "phone-screening",
    rating: 3,
    tags: [],
    isInternal: false,
    pulseProfile: null,
    teamFitScore: null,
    appliedDate: "2026-05-18",
    source: "agency",
  },
  {
    id: 109,
    jobId: 3,
    name: "Mathilde Holm",
    email: "mathilde@example.com",
    location: "Copenhagen",
    linkedIn: "linkedin.com/in/mathildeholm",
    currentStage: "group-interview",
    rating: 5,
    tags: ["Service-design portfolio"],
    isInternal: false,
    pulseProfile: {
      primary: "supporter",
      secondary: "energizer",
      scores: { driver: 28, energizer: 71, supporter: 84, analyst: 44 },
      wheelPosition: "Energizing Supporter",
      confidence: 81,
    },
    teamFitScore: 86,
    appliedDate: "2026-05-15",
    source: "direct",
  },
  {
    id: 110,
    jobId: 3,
    name: "Jakob Kjær",
    email: "jakob@example.com",
    location: "Copenhagen",
    linkedIn: "linkedin.com/in/jakobkjaer",
    currentStage: "reviewing",
    rating: 4,
    tags: [],
    isInternal: false,
    pulseProfile: {
      primary: "energizer",
      secondary: "supporter",
      scores: { driver: 38, energizer: 79, supporter: 65, analyst: 47 },
      wheelPosition: "Supportive Energizer",
      confidence: 70,
    },
    teamFitScore: 74,
    appliedDate: "2026-05-23",
    source: "linkedin",
  },
  {
    id: 111,
    jobId: 3,
    name: "Saga Lindqvist",
    email: "saga.lindqvist@valtech.com",
    location: "Stockholm",
    linkedIn: "linkedin.com/in/sagalindqvist",
    currentStage: "manager-interview",
    rating: 5,
    tags: ["Internal candidate", "Pitch board referral"],
    isInternal: true,
    pulseProfile: {
      primary: "energizer",
      secondary: "supporter",
      scores: { driver: 33, energizer: 86, supporter: 72, analyst: 38 },
      wheelPosition: "Supportive Energizer",
      confidence: 95,
    },
    teamFitScore: 91,
    appliedDate: "2026-05-20",
    source: "internal",
  },
  {
    id: 112,
    jobId: 4,
    name: "Aino Salminen",
    email: "aino@example.com",
    location: "Helsinki",
    linkedIn: "linkedin.com/in/ainosalminen",
    currentStage: "phone-screening",
    rating: 4,
    tags: ["ML PhD"],
    isInternal: false,
    pulseProfile: {
      primary: "analyst",
      secondary: "driver",
      scores: { driver: 56, energizer: 31, supporter: 38, analyst: 89 },
      wheelPosition: "Driving Analyst",
      confidence: 76,
    },
    teamFitScore: 79,
    appliedDate: "2026-05-09",
    source: "direct",
  },
  {
    id: 113,
    jobId: 4,
    name: "Mikko Räsänen",
    email: "mikko@example.com",
    location: "Tampere",
    linkedIn: "linkedin.com/in/mikkorasanen",
    currentStage: "manager-interview",
    rating: 5,
    tags: ["Strong publications"],
    isInternal: false,
    pulseProfile: {
      primary: "analyst",
      secondary: "supporter",
      scores: { driver: 32, energizer: 28, supporter: 60, analyst: 87 },
      wheelPosition: "Supportive Analyst",
      confidence: 82,
    },
    teamFitScore: 83,
    appliedDate: "2026-05-02",
    source: "linkedin",
  },
  {
    id: 114,
    jobId: 4,
    name: "Henna Mäkinen",
    email: "henna.makinen@valtech.com",
    location: "Helsinki",
    linkedIn: "linkedin.com/in/hennamakinen",
    currentStage: "reference-check",
    rating: 5,
    tags: ["Internal candidate"],
    isInternal: true,
    pulseProfile: {
      primary: "analyst",
      secondary: "driver",
      scores: { driver: 58, energizer: 31, supporter: 39, analyst: 88 },
      wheelPosition: "Driving Analyst",
      confidence: 94,
    },
    teamFitScore: 90,
    appliedDate: "2026-05-25",
    source: "internal",
  },
  {
    id: 115,
    jobId: 1,
    name: "Niklas Bergquist",
    email: "niklas@example.com",
    location: "Stockholm",
    linkedIn: "linkedin.com/in/niklasbergquist",
    currentStage: "hired",
    rating: 5,
    tags: ["Hired — start 2026-06-15"],
    isInternal: false,
    pulseProfile: {
      primary: "energizer",
      secondary: "analyst",
      scores: { driver: 36, energizer: 80, supporter: 50, analyst: 70 },
      wheelPosition: "Energizer",
      confidence: 85,
    },
    teamFitScore: 87,
    appliedDate: "2026-04-02",
    source: "linkedin",
  },
];
