import type { Brief, PitchRole } from "./types";

export const seedBriefs: Brief[] = [
  {
    id: 1,
    name: "Klarna CX Transformation — Phase 2",
    client: "Klarna",
    market: "Stockholm",
    stage: "active",
    startDate: "2026-02-01",
    duration: "9 months",
    harmonyScore: 82,
    teamIds: [1, 7, 11],
    priority: "normal",
    briefType: "Delivery programme",
    daysToStart: null,
    scope: "Phase 2 of Klarna's customer-experience transformation. Re-platform the checkout, onboarding, and dispute resolution flows on a new event-driven backend, with refreshed design language and accessibility baseline.",
    context: "Klarna's NPS dipped sharply during phase 1 of the migration. Phase 2 focuses on restoring trust through measurable UX improvement and operational stability. Programme reports into Klarna's CPO and the Valtech engagement director Linnea Sjöberg is the senior relationship lead.",
    budget: "€2.4M",
    requiredEnergy: { driver: "essential", energizer: "high", supporter: "medium", analyst: "high" },
    roles: [
      {
        id: 101,
        title: "Engagement Director",
        level: "lead",
        requiredEnergy: "driver",
        skills: ["Engagement leadership", "Client partnership", "Programme delivery"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "9 months",
        dayRateBandEur: { min: 2800, max: 3500 },
        description: "Owns the Klarna relationship end-to-end. Runs steering meetings with the CPO, manages senior stakeholders, and protects the delivery team from scope creep.",
      },
      {
        id: 102,
        title: "Principal Tech Lead",
        level: "lead",
        requiredEnergy: "analyst",
        skills: ["Event-driven architecture", "AWS", "Distributed systems"],
        openings: 1,
        filled: 0,
        applicants: 3,
        duration: "9 months",
        dayRateBandEur: { min: 2500, max: 3200 },
        description: "Technical owner for the new event-driven backend. Defines the architecture, partners with Klarna's principal engineers, and reviews every major design decision.",
      },
      {
        id: 103,
        title: "Senior Product Designer",
        level: "senior",
        requiredEnergy: "energizer",
        skills: ["Product design", "Design systems", "Accessibility"],
        openings: 2,
        filled: 1,
        applicants: 5,
        duration: "9 months",
        dayRateBandEur: { min: 1800, max: 2400 },
        description: "Leads the design refresh across checkout, onboarding, and disputes. Pairs daily with engineering and runs fortnightly playback sessions with Klarna's product team.",
      },
    ],
  },
  {
    id: 2,
    name: "Maersk shipment events platform v3",
    client: "Maersk",
    market: "Copenhagen",
    stage: "active",
    startDate: "2026-01-15",
    duration: "12 months",
    harmonyScore: 76,
    teamIds: [2, 8],
    priority: "normal",
    briefType: "Engineering rebuild",
    daysToStart: null,
    scope: "v3 of the Maersk container shipment events platform. Replaces the legacy SOAP/JMS stack with a Kafka-based event mesh serving real-time container tracking to 11 internal systems and external customer portals.",
    context: "Maersk's current platform is at end-of-life with the legacy vendor sunsetting support. v3 is mission-critical — every Maersk container shipment depends on this telemetry. 99.99% uptime SLA. Mathias Lund is the principal architect.",
    budget: "€3.1M",
    requiredEnergy: { driver: "low", energizer: "low", supporter: "medium", analyst: "essential" },
    roles: [
      {
        id: 201,
        title: "Principal Architect",
        level: "lead",
        requiredEnergy: "analyst",
        skills: ["Event-driven systems", "Kafka", "AWS"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "12 months",
        dayRateBandEur: { min: 2800, max: 3500 },
        description: "Architectural owner of the migration. Defines the event mesh design, partners with Maersk's enterprise architecture team, and signs off every breaking change.",
      },
      {
        id: 202,
        title: "Senior Backend Engineer",
        level: "senior",
        requiredEnergy: "analyst",
        skills: ["Go", "Kafka", "Postgres performance"],
        openings: 3,
        filled: 2,
        applicants: 4,
        duration: "12 months",
        dayRateBandEur: { min: 1800, max: 2400 },
        description: "Builds and owns one or two services in the new event mesh. Pairs with Maersk's internal engineers and ships through their CI/CD pipeline.",
      },
      {
        id: 203,
        title: "Delivery Lead",
        level: "lead",
        requiredEnergy: "supporter",
        skills: ["Programme management", "Risk management", "Stakeholder governance"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "12 months",
        dayRateBandEur: { min: 2400, max: 2900 },
        description: "Runs the day-to-day delivery. Sprint cadence, risk register, weekly governance with Maersk leadership.",
      },
    ],
  },
  {
    id: 3,
    name: "H&M Commerce — checkout redesign",
    client: "H&M",
    market: "Stockholm",
    stage: "active",
    startDate: "2026-03-10",
    duration: "5 months",
    harmonyScore: 79,
    teamIds: [11, 7],
    priority: "normal",
    briefType: "Product design",
    daysToStart: null,
    scope: "Full redesign of the H&M checkout experience across web and mobile web. Reduce cart abandonment, improve guest checkout, modernise the address + payment flows. Includes A/B testing infrastructure.",
    context: "H&M's checkout conversion is materially below benchmark. Astrid Falk is the client partner and Saga Lindqvist is leading the design work. Tight commercial pressure — every percentage point of conversion improvement is meaningful at H&M's scale.",
    budget: "€820k",
    requiredEnergy: { driver: "high", energizer: "high", supporter: "medium", analyst: "medium" },
    roles: [
      {
        id: 301,
        title: "Client Partner",
        level: "lead",
        requiredEnergy: "driver",
        skills: ["Client partnership", "Negotiation", "Account leadership"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "5 months",
        dayRateBandEur: { min: 2800, max: 3500 },
        description: "Owns the H&M relationship at executive level. Steers commercials, handles escalations, and orchestrates the renewal conversation.",
      },
      {
        id: 302,
        title: "Senior Product Designer",
        level: "senior",
        requiredEnergy: "energizer",
        skills: ["Product design", "Conversion optimisation", "Prototyping"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "5 months",
        dayRateBandEur: { min: 1800, max: 2400 },
        description: "Leads the checkout redesign. Owns research, prototyping, and weekly playbacks with H&M's product team.",
      },
    ],
  },
  {
    id: 4,
    name: "OP Financial demand model",
    client: "OP Financial",
    market: "Helsinki",
    stage: "confirmed",
    startDate: "2026-06-01",
    duration: "4 months",
    harmonyScore: 71,
    teamIds: [5],
    priority: "normal",
    briefType: "Applied ML",
    daysToStart: 4,
    scope: "Build a customer demand-forecasting model for OP Financial's retail banking products. Pilot across three regional markets, target a 15% reduction in branch over/under-staffing.",
    context: "OP has run two failed internal attempts at this. They want a Valtech-led model with a 16-week timebox, transparent methodology, and clear handover documentation. Henna Mäkinen is the data science lead.",
    budget: "€420k",
    requiredEnergy: { driver: "medium", energizer: "low", supporter: "low", analyst: "essential" },
    roles: [
      {
        id: 401,
        title: "Senior Data Scientist",
        level: "senior",
        requiredEnergy: "analyst",
        skills: ["Applied ML", "Forecasting", "Time-series"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "4 months",
        dayRateBandEur: { min: 1800, max: 2400 },
        description: "Owns model design and delivery. Partners with OP's internal analytics team and presents to their CDO at the mid-point and end.",
      },
      {
        id: 402,
        title: "MLOps Engineer",
        level: "mid",
        requiredEnergy: "analyst",
        skills: ["MLOps", "Python", "AWS Sagemaker"],
        openings: 1,
        filled: 0,
        applicants: 2,
        duration: "4 months",
        dayRateBandEur: { min: 1400, max: 1900 },
        description: "Productionises the model. Sets up the training pipeline, monitoring, and the handover documentation.",
      },
    ],
  },
  {
    id: 5,
    name: "Storebrand member portal rebuild",
    client: "Storebrand",
    market: "Oslo",
    stage: "confirmed",
    startDate: "2026-06-09",
    duration: "7 months",
    harmonyScore: 74,
    teamIds: [9, 12],
    priority: "normal",
    briefType: "Frontend rebuild",
    daysToStart: 12,
    scope: "Complete rebuild of Storebrand's member self-service portal. Migration from legacy Angular 1.x to Next.js, full responsive overhaul, Lighthouse 95+ target on launch.",
    context: "Storebrand is consolidating three legacy member portals into one. Ida Sørensen led the discovery and will continue as the frontend lead. Magnus Dahl is the engineering manager.",
    budget: "€1.1M",
    requiredEnergy: { driver: "medium", energizer: "high", supporter: "medium", analyst: "high" },
    roles: [
      {
        id: 501,
        title: "Engineering Manager",
        level: "lead",
        requiredEnergy: "driver",
        skills: ["Engineering management", "Hiring", "Technical strategy"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "7 months",
        dayRateBandEur: { min: 2400, max: 2900 },
        description: "Owns delivery and team performance. Reports to Storebrand's CTO at fortnightly intervals.",
      },
      {
        id: 502,
        title: "Senior Frontend Engineer",
        level: "senior",
        requiredEnergy: "energizer",
        skills: ["React", "Next.js", "TypeScript", "Accessibility"],
        openings: 2,
        filled: 1,
        applicants: 4,
        duration: "7 months",
        dayRateBandEur: { min: 1700, max: 2200 },
        description: "Builds the portal's core member flows. Pairs with Storebrand's internal designers and one of their backend teams.",
      },
    ],
  },
  {
    id: 6,
    name: "Equinor innovation lab — strand 2",
    client: "Equinor",
    market: "Oslo",
    stage: "buyin",
    startDate: "2026-07-01",
    duration: "3 months",
    harmonyScore: 68,
    teamIds: [4],
    priority: "normal",
    briefType: "Strategy + facilitation",
    daysToStart: 34,
    scope: "Three-month sprint to scope and prototype two ventures emerging from strand 1 of Equinor's customer innovation lab. Combine workshop facilitation with rapid prototyping.",
    context: "Strand 1 generated 14 venture concepts. Strand 2 narrows to two for prototyping. Aksel Berg led strand 1 and is the natural lead for strand 2.",
    budget: "€340k",
    requiredEnergy: { driver: "high", energizer: "essential", supporter: "low", analyst: "low" },
    roles: [
      {
        id: 601,
        title: "Strategy Lead",
        level: "lead",
        requiredEnergy: "energizer",
        skills: ["Innovation strategy", "Workshop facilitation", "Storytelling"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "3 months",
        dayRateBandEur: { min: 2200, max: 2800 },
        description: "Runs the venture-shaping workshops, owns the narrative, and presents to Equinor's innovation board at the end.",
      },
      {
        id: 602,
        title: "Senior Prototyper (Design Engineer)",
        level: "senior",
        requiredEnergy: "energizer",
        skills: ["Rapid prototyping", "React", "Figma-to-code"],
        openings: 2,
        filled: 0,
        applicants: 2,
        duration: "3 months",
        dayRateBandEur: { min: 1700, max: 2200 },
        description: "Builds high-fidelity prototypes of the two shortlisted ventures. Daily pairing with the strategy lead.",
      },
    ],
  },
  {
    id: 7,
    name: "DSB digital experience platform",
    client: "DSB",
    market: "Copenhagen",
    stage: "buyin",
    startDate: "2026-08-01",
    duration: "10 months",
    harmonyScore: 73,
    teamIds: [3, 8],
    priority: "normal",
    briefType: "Service design + delivery",
    daysToStart: 65,
    scope: "Multi-year digital experience platform programme for DSB (Danish State Railways). Unified booking, account, journey-management and disruption-communication experience.",
    context: "DSB has commissioned this through a formal procurement. Pernille Andersen led the bid response and will be the engagement director.",
    budget: "€4.6M",
    requiredEnergy: { driver: "medium", energizer: "medium", supporter: "essential", analyst: "high" },
    roles: [
      {
        id: 701,
        title: "UX Director",
        level: "lead",
        requiredEnergy: "supporter",
        skills: ["Service design", "Workshop facilitation", "Team coaching"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "10 months",
        dayRateBandEur: { min: 2800, max: 3500 },
        description: "Owns the customer experience across all the touchpoints. Leads the design team, presents to DSB's senior leadership monthly.",
      },
      {
        id: 702,
        title: "Delivery Lead",
        level: "lead",
        requiredEnergy: "supporter",
        skills: ["Programme management", "Agile delivery", "Client governance"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "10 months",
        dayRateBandEur: { min: 2400, max: 2900 },
        description: "Owns delivery health. Steering with DSB's programme office, weekly status, fortnightly demo.",
      },
      {
        id: 703,
        title: "Senior Service Designer",
        level: "senior",
        requiredEnergy: "supporter",
        skills: ["Service design", "Journey mapping", "Stakeholder co-design"],
        openings: 2,
        filled: 0,
        applicants: 3,
        duration: "10 months",
        dayRateBandEur: { min: 1800, max: 2400 },
        description: "Maps the end-to-end customer experience. Runs co-design workshops with DSB staff and real passengers.",
      },
    ],
  },
  {
    id: 8,
    name: "Nordea wealth portal — discovery",
    client: "Nordea",
    market: "Stockholm",
    stage: "proposed",
    startDate: "2026-07-15",
    duration: "2 months",
    harmonyScore: 70,
    teamIds: [11, 1],
    priority: "urgent",
    briefType: "Discovery + pitch",
    daysToStart: 48,
    scope: "Eight-week discovery for Nordea's high-net-worth wealth-management portal. Outcome is a roadmap and high-fidelity prototypes ready to brief a build phase.",
    context: "Competitive bid. Pitch closes Friday. Linnea Sjöberg leads the response, Astrid Falk is on the client team. We have a strong existing Nordea relationship — losing this would be material.",
    budget: "€280k",
    requiredEnergy: { driver: "essential", energizer: "high", supporter: "low", analyst: "medium" },
    roles: [
      {
        id: 801,
        title: "Pitch Director",
        level: "lead",
        requiredEnergy: "driver",
        skills: ["Pitch leadership", "C-suite facilitation", "Storytelling"],
        openings: 1,
        filled: 0,
        applicants: 5,
        duration: "2 months",
        dayRateBandEur: { min: 2800, max: 3500 },
        description: "Owns the response. Pulls the proposal together, runs rehearsals, presents to Nordea's executive committee.",
      },
      {
        id: 802,
        title: "Wealth UX Lead",
        level: "lead",
        requiredEnergy: "energizer",
        skills: ["UX leadership", "Financial services", "Prototyping"],
        openings: 1,
        filled: 0,
        applicants: 2,
        duration: "2 months",
        dayRateBandEur: { min: 2200, max: 2800 },
        description: "Leads the discovery design work. Domain experience in wealth/private banking strongly preferred.",
      },
    ],
  },
  {
    id: 9,
    name: "Telia self-service v2",
    client: "Telia",
    market: "Stockholm",
    stage: "proposed",
    startDate: "2026-09-01",
    duration: "8 months",
    harmonyScore: 75,
    teamIds: [7, 6],
    priority: "normal",
    briefType: "Product design + engineering",
    daysToStart: 96,
    scope: "Major version bump of Telia's customer self-service portal. New design system, modernised tooling, simplified plan management and billing.",
    context: "v1 was delivered by Valtech in 2024 and is now end-of-life on its tech stack. Saga Lindqvist designed v1 and is the natural continuity.",
    budget: "€1.4M",
    requiredEnergy: { driver: "medium", energizer: "high", supporter: "medium", analyst: "high" },
    roles: [
      {
        id: 901,
        title: "UX Lead",
        level: "lead",
        requiredEnergy: "energizer",
        skills: ["Product design", "Design systems", "Prototyping"],
        openings: 1,
        filled: 1,
        applicants: 3,
        duration: "8 months",
        dayRateBandEur: { min: 2200, max: 2800 },
        description: "Leads UX across the rebuild. Owns the design system refresh and pairs with Telia's product owners.",
      },
      {
        id: 902,
        title: "Solutions Architect",
        level: "senior",
        requiredEnergy: "analyst",
        skills: ["Cloud architecture", "API design", "Migration"],
        openings: 1,
        filled: 0,
        applicants: 1,
        duration: "8 months",
        dayRateBandEur: { min: 2200, max: 2800 },
        description: "Owns the technical architecture. Migration story off the legacy stack, integration with Telia's internal services.",
      },
    ],
  },
  {
    id: 10,
    name: "Carlsberg loyalty programme — phase 3",
    client: "Carlsberg",
    market: "Copenhagen",
    stage: "analysing",
    startDate: "2026-08-15",
    duration: "6 months",
    harmonyScore: null,
    teamIds: [8, 3],
    priority: "normal",
    briefType: "Delivery + UX",
    daysToStart: 79,
    scope: "Phase 3 of Carlsberg's consumer loyalty programme. Add gamification, refresh the mobile UI, integrate with three more partner brands.",
    context: "Phases 1 and 2 went well. Carlsberg's marketing director wants the same Valtech team where possible. Tobias Krogh is the delivery lead.",
    budget: "€680k",
    requiredEnergy: { driver: "medium", energizer: "medium", supporter: "essential", analyst: "medium" },
    roles: [
      {
        id: 1001,
        title: "Delivery Lead",
        level: "lead",
        requiredEnergy: "supporter",
        skills: ["Programme management", "Mobile delivery", "Client governance"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "6 months",
        dayRateBandEur: { min: 2400, max: 2900 },
        description: "Owns delivery. Continuity from phase 2 — Tobias Krogh is the named lead.",
      },
      {
        id: 1002,
        title: "Mobile Product Designer",
        level: "senior",
        requiredEnergy: "energizer",
        skills: ["Mobile design", "Gamification", "Prototyping"],
        openings: 1,
        filled: 0,
        applicants: 2,
        duration: "6 months",
        dayRateBandEur: { min: 1700, max: 2200 },
        description: "Owns the gamification design surface. Works closely with Carlsberg's brand team.",
      },
    ],
  },
  {
    id: 11,
    name: "SAS Group customer cloud — migration discovery",
    client: "SAS Group",
    market: "Stockholm",
    stage: "analysing",
    startDate: "2026-09-15",
    duration: "3 months",
    harmonyScore: null,
    teamIds: [6],
    priority: "low",
    briefType: "Architecture discovery",
    daysToStart: 110,
    scope: "Twelve-week architecture discovery. Map SAS Group's current customer-facing systems and produce a target cloud architecture for migration.",
    context: "SAS is exploring options. This is exploratory — no commitment to migration yet. Erik Holm led the original customer platform migration off mainframe in 2024.",
    budget: "€220k",
    requiredEnergy: { driver: "low", energizer: "low", supporter: "medium", analyst: "essential" },
    roles: [
      {
        id: 1101,
        title: "Principal Solutions Architect",
        level: "lead",
        requiredEnergy: "analyst",
        skills: ["Enterprise architecture", "Cloud migration", "Technical writing"],
        openings: 1,
        filled: 1,
        applicants: 0,
        duration: "3 months",
        dayRateBandEur: { min: 2800, max: 3500 },
        description: "Owns the discovery output. Continuity from the 2024 work — Erik Holm is the named lead.",
      },
    ],
  },
  {
    id: 12,
    name: "Volvo Cars connected platform — extension",
    client: "Volvo Cars",
    market: "Stockholm",
    stage: "unstaffed",
    startDate: "2026-09-01",
    duration: "12 months",
    harmonyScore: null,
    teamIds: [],
    priority: "urgent",
    briefType: "Engineering programme",
    daysToStart: 96,
    scope: "Twelve-month extension of Volvo Cars' connected-vehicle data platform. New telemetry pipelines, expanded mobile companion app, EV charging integration.",
    context: "Volvo Cars want this confirmed within four weeks. We have an existing relationship through Magnus Dahl. Largest unstaffed brief on the board this quarter.",
    budget: "€3.8M",
    requiredEnergy: { driver: "high", energizer: "medium", supporter: "medium", analyst: "essential" },
    roles: [
      {
        id: 1201,
        title: "Engineering Lead",
        level: "lead",
        requiredEnergy: "driver",
        skills: ["Engineering management", "Cloud architecture", "Programme delivery"],
        openings: 1,
        filled: 0,
        applicants: 4,
        duration: "12 months",
        dayRateBandEur: { min: 2800, max: 3500 },
        description: "Top of the must-staff list. Owns engineering across all workstreams.",
      },
      {
        id: 1202,
        title: "Senior Data Engineer",
        level: "senior",
        requiredEnergy: "analyst",
        skills: ["Data pipelines", "Streaming", "AWS"],
        openings: 3,
        filled: 0,
        applicants: 3,
        duration: "12 months",
        dayRateBandEur: { min: 1800, max: 2400 },
        description: "Builds the telemetry pipelines. Three openings, very specific skill profile.",
      },
      {
        id: 1203,
        title: "Senior Mobile Engineer",
        level: "senior",
        requiredEnergy: "energizer",
        skills: ["React Native", "iOS", "Android"],
        openings: 2,
        filled: 0,
        applicants: 2,
        duration: "12 months",
        dayRateBandEur: { min: 1700, max: 2200 },
        description: "Builds the companion app. Pairs with Volvo's internal mobile team.",
      },
    ],
  },
  {
    id: 13,
    name: "Kesko grocery — demand forecasting",
    client: "Kesko",
    market: "Helsinki",
    stage: "unstaffed",
    startDate: "2026-08-01",
    duration: "5 months",
    harmonyScore: null,
    teamIds: [],
    priority: "urgent",
    briefType: "Applied ML",
    daysToStart: 65,
    scope: "Demand-forecasting model for Kesko's grocery store network. Pilot in 40 stores, target inventory waste reduction of 12%+.",
    context: "Kesko's CDO has approved the budget but we need to staff this immediately to meet the August start. Henna Mäkinen would be ideal but is allocated.",
    budget: "€520k",
    requiredEnergy: { driver: "low", energizer: "low", supporter: "low", analyst: "essential" },
    roles: [
      {
        id: 1301,
        title: "Senior Data Scientist",
        level: "senior",
        requiredEnergy: "analyst",
        skills: ["Applied ML", "Forecasting", "Time-series"],
        openings: 1,
        filled: 0,
        applicants: 2,
        duration: "5 months",
        dayRateBandEur: { min: 1800, max: 2400 },
        description: "Owns the model. Pilot design, training, validation, and the executive readout at month 5.",
      },
    ],
  },
  {
    id: 14,
    name: "IKEA experience platform — UX strand",
    client: "IKEA",
    market: "Stockholm",
    stage: "unstaffed",
    startDate: "2026-08-25",
    duration: "9 months",
    harmonyScore: null,
    teamIds: [],
    priority: "normal",
    briefType: "Product design",
    daysToStart: 89,
    scope: "Nine-month UX strand contributing to IKEA's broader experience-platform rebuild. Service-design lens, journey mapping, and a co-design lab with IKEA's in-house design team.",
    context: "IKEA's design organisation is mature — we'll work as embedded partners, not as a separate vendor. Saga Lindqvist has a long-standing IKEA relationship.",
    budget: "€1.2M",
    requiredEnergy: { driver: "medium", energizer: "essential", supporter: "high", analyst: "low" },
    roles: [
      {
        id: 1401,
        title: "Senior Product Designer",
        level: "senior",
        requiredEnergy: "energizer",
        skills: ["Service design", "Design systems", "Workshop facilitation"],
        openings: 2,
        filled: 0,
        applicants: 6,
        duration: "9 months",
        dayRateBandEur: { min: 1800, max: 2400 },
        description: "Embedded in IKEA's design org. Owns journey strands and runs the co-design lab.",
      },
    ],
  },
  {
    id: 15,
    name: "Posten Norge logistics — phase 4",
    client: "Posten Norge",
    market: "Oslo",
    stage: "unstaffed",
    startDate: "2026-09-15",
    duration: "8 months",
    harmonyScore: null,
    teamIds: [],
    priority: "low",
    briefType: "Engineering programme",
    daysToStart: 110,
    scope: "Phase 4 of Posten Norge's logistics platform rebuild. Last-mile delivery optimisation, driver-facing app, integration with the new sorting facility in Oslo.",
    context: "Phases 1-3 went well. Phase 4 is exploratory at low priority while Posten Norge confirms internal funding.",
    budget: "€1.9M",
    requiredEnergy: { driver: "essential", energizer: "low", supporter: "medium", analyst: "high" },
    roles: [
      {
        id: 1501,
        title: "Senior Backend Engineer",
        level: "senior",
        requiredEnergy: "analyst",
        skills: ["Go", "Event-driven systems", "API security"],
        openings: 2,
        filled: 0,
        applicants: 1,
        duration: "8 months",
        dayRateBandEur: { min: 1800, max: 2400 },
        description: "Owns one workstream — most likely the routing optimisation service. Continuity from phase 3 preferred.",
      },
    ],
  },
];

export const seedPitchRoles: PitchRole[] = [
  {
    id: 1,
    briefId: 12,
    title: "Engineering Lead",
    briefName: "Volvo Cars connected platform — extension",
    market: "Stockholm",
    duration: "12 months",
    startDate: "2026-09-01",
    level: "lead",
    requiredEnergy: "driver",
    skills: ["Engineering management", "Cloud architecture", "Programme delivery"],
    applicantCount: 4,
    closingDate: "2026-06-15",
    creditsOnSelection: 80,
    postedDaysAgo: 3,
  },
  {
    id: 2,
    briefId: 13,
    title: "Senior Data Scientist",
    briefName: "Kesko grocery — demand forecasting",
    market: "Helsinki",
    duration: "5 months",
    startDate: "2026-08-01",
    level: "senior",
    requiredEnergy: "analyst",
    skills: ["Applied ML", "Forecasting", "Time-series"],
    applicantCount: 2,
    closingDate: "2026-06-10",
    creditsOnSelection: 60,
    postedDaysAgo: 5,
  },
  {
    id: 3,
    briefId: 14,
    title: "Senior Product Designer",
    briefName: "IKEA experience platform — UX strand",
    market: "Stockholm",
    duration: "9 months",
    startDate: "2026-08-25",
    level: "senior",
    requiredEnergy: "energizer",
    skills: ["Service design", "Design systems", "Workshop facilitation"],
    applicantCount: 6,
    closingDate: "2026-06-20",
    creditsOnSelection: 60,
    postedDaysAgo: 2,
  },
  {
    id: 4,
    briefId: 15,
    title: "Senior Backend Engineer",
    briefName: "Posten Norge logistics — phase 4",
    market: "Oslo",
    duration: "8 months",
    startDate: "2026-09-15",
    level: "senior",
    requiredEnergy: "analyst",
    skills: ["Go", "Event-driven systems", "API security"],
    applicantCount: 1,
    closingDate: "2026-07-01",
    creditsOnSelection: 60,
    postedDaysAgo: 1,
  },
  {
    id: 5,
    briefId: 9,
    title: "UX Lead",
    briefName: "Telia self-service v2",
    market: "Stockholm",
    duration: "8 months",
    startDate: "2026-09-01",
    level: "lead",
    requiredEnergy: "energizer",
    skills: ["Product design", "UX leadership", "Prototyping"],
    applicantCount: 3,
    closingDate: "2026-06-25",
    creditsOnSelection: 80,
    postedDaysAgo: 4,
  },
  {
    id: 6,
    briefId: 7,
    title: "Delivery Lead",
    briefName: "DSB digital experience platform",
    market: "Copenhagen",
    duration: "10 months",
    startDate: "2026-08-01",
    level: "lead",
    requiredEnergy: "supporter",
    skills: ["Programme management", "Agile delivery", "Client governance"],
    applicantCount: 2,
    closingDate: "2026-06-30",
    creditsOnSelection: 80,
    postedDaysAgo: 6,
  },
  {
    id: 7,
    briefId: 8,
    title: "Pitch Director",
    briefName: "Nordea wealth portal — discovery",
    market: "Stockholm",
    duration: "2 months",
    startDate: "2026-07-15",
    level: "lead",
    requiredEnergy: "driver",
    skills: ["Pitch leadership", "C-suite facilitation", "Storytelling"],
    applicantCount: 5,
    closingDate: "2026-06-05",
    creditsOnSelection: 100,
    postedDaysAgo: 1,
  },
  {
    id: 8,
    briefId: 6,
    title: "Strategy Consultant",
    briefName: "Equinor innovation lab — strand 2",
    market: "Oslo",
    duration: "3 months",
    startDate: "2026-07-01",
    level: "mid",
    requiredEnergy: "energizer",
    skills: ["Innovation strategy", "Workshop facilitation"],
    applicantCount: 2,
    closingDate: "2026-06-20",
    creditsOnSelection: 40,
    postedDaysAgo: 7,
  },
];
