import type { Brief, PitchRole } from "./types";

export const seedBriefs: Brief[] = [
  {
    id: 1,
    name: "Klarna CX Transformation — Phase 2",
    client: "Klarna",
    market: "Stockholm",
    stage: "active",
    startDate: "2026-02-01",
    duration: "9 months",
    harmonyScore: 82,
    teamIds: [1, 7, 11],
    priority: "normal",
    briefType: "Delivery programme",
    daysToStart: null,
    requiredEnergy: { driver: "essential", energizer: "high", supporter: "medium", analyst: "high" },
  },
  {
    id: 2,
    name: "Maersk shipment events platform v3",
    client: "Maersk",
    market: "Copenhagen",
    stage: "active",
    startDate: "2026-01-15",
    duration: "12 months",
    harmonyScore: 76,
    teamIds: [2, 8],
    priority: "normal",
    briefType: "Engineering rebuild",
    daysToStart: null,
    requiredEnergy: { driver: "low", energizer: "low", supporter: "medium", analyst: "essential" },
  },
  {
    id: 3,
    name: "H&M Commerce — checkout redesign",
    client: "H&M",
    market: "Stockholm",
    stage: "active",
    startDate: "2026-03-10",
    duration: "5 months",
    harmonyScore: 79,
    teamIds: [11, 7],
    priority: "normal",
    briefType: "Product design",
    daysToStart: null,
    requiredEnergy: { driver: "high", energizer: "high", supporter: "medium", analyst: "medium" },
  },
  {
    id: 4,
    name: "OP Financial demand model",
    client: "OP Financial",
    market: "Helsinki",
    stage: "confirmed",
    startDate: "2026-06-01",
    duration: "4 months",
    harmonyScore: 71,
    teamIds: [5],
    priority: "normal",
    briefType: "Applied ML",
    daysToStart: 4,
    requiredEnergy: { driver: "medium", energizer: "low", supporter: "low", analyst: "essential" },
  },
  {
    id: 5,
    name: "Storebrand member portal rebuild",
    client: "Storebrand",
    market: "Oslo",
    stage: "confirmed",
    startDate: "2026-06-09",
    duration: "7 months",
    harmonyScore: 74,
    teamIds: [9, 12],
    priority: "normal",
    briefType: "Frontend rebuild",
    daysToStart: 12,
    requiredEnergy: { driver: "medium", energizer: "high", supporter: "medium", analyst: "high" },
  },
  {
    id: 6,
    name: "Equinor innovation lab — strand 2",
    client: "Equinor",
    market: "Oslo",
    stage: "buyin",
    startDate: "2026-07-01",
    duration: "3 months",
    harmonyScore: 68,
    teamIds: [4],
    priority: "normal",
    briefType: "Strategy + facilitation",
    daysToStart: 34,
    requiredEnergy: { driver: "high", energizer: "essential", supporter: "low", analyst: "low" },
  },
  {
    id: 7,
    name: "DSB digital experience platform",
    client: "DSB",
    market: "Copenhagen",
    stage: "buyin",
    startDate: "2026-08-01",
    duration: "10 months",
    harmonyScore: 73,
    teamIds: [3, 8],
    priority: "normal",
    briefType: "Service design + delivery",
    daysToStart: 65,
    requiredEnergy: { driver: "medium", energizer: "medium", supporter: "essential", analyst: "high" },
  },
  {
    id: 8,
    name: "Nordea wealth portal — discovery",
    client: "Nordea",
    market: "Stockholm",
    stage: "proposed",
    startDate: "2026-07-15",
    duration: "2 months",
    harmonyScore: 70,
    teamIds: [11, 1],
    priority: "urgent",
    briefType: "Discovery + pitch",
    daysToStart: 48,
    requiredEnergy: { driver: "essential", energizer: "high", supporter: "low", analyst: "medium" },
  },
  {
    id: 9,
    name: "Telia self-service v2",
    client: "Telia",
    market: "Stockholm",
    stage: "proposed",
    startDate: "2026-09-01",
    duration: "8 months",
    harmonyScore: 75,
    teamIds: [7, 6],
    priority: "normal",
    briefType: "Product design + engineering",
    daysToStart: 96,
    requiredEnergy: { driver: "medium", energizer: "high", supporter: "medium", analyst: "high" },
  },
  {
    id: 10,
    name: "Carlsberg loyalty programme — phase 3",
    client: "Carlsberg",
    market: "Copenhagen",
    stage: "analysing",
    startDate: "2026-08-15",
    duration: "6 months",
    harmonyScore: null,
    teamIds: [8, 3],
    priority: "normal",
    briefType: "Delivery + UX",
    daysToStart: 79,
    requiredEnergy: { driver: "medium", energizer: "medium", supporter: "essential", analyst: "medium" },
  },
  {
    id: 11,
    name: "SAS Group customer cloud — migration discovery",
    client: "SAS Group",
    market: "Stockholm",
    stage: "analysing",
    startDate: "2026-09-15",
    duration: "3 months",
    harmonyScore: null,
    teamIds: [6],
    priority: "low",
    briefType: "Architecture discovery",
    daysToStart: 110,
    requiredEnergy: { driver: "low", energizer: "low", supporter: "medium", analyst: "essential" },
  },
  {
    id: 12,
    name: "Volvo Cars connected platform — extension",
    client: "Volvo Cars",
    market: "Stockholm",
    stage: "unstaffed",
    startDate: "2026-09-01",
    duration: "12 months",
    harmonyScore: null,
    teamIds: [],
    priority: "urgent",
    briefType: "Engineering programme",
    daysToStart: 96,
    requiredEnergy: { driver: "high", energizer: "medium", supporter: "medium", analyst: "essential" },
  },
  {
    id: 13,
    name: "Kesko grocery — demand forecasting",
    client: "Kesko",
    market: "Helsinki",
    stage: "unstaffed",
    startDate: "2026-08-01",
    duration: "5 months",
    harmonyScore: null,
    teamIds: [],
    priority: "urgent",
    briefType: "Applied ML",
    daysToStart: 65,
    requiredEnergy: { driver: "low", energizer: "low", supporter: "low", analyst: "essential" },
  },
  {
    id: 14,
    name: "IKEA experience platform — UX strand",
    client: "IKEA",
    market: "Stockholm",
    stage: "unstaffed",
    startDate: "2026-08-25",
    duration: "9 months",
    harmonyScore: null,
    teamIds: [],
    priority: "normal",
    briefType: "Product design",
    daysToStart: 89,
    requiredEnergy: { driver: "medium", energizer: "essential", supporter: "high", analyst: "low" },
  },
  {
    id: 15,
    name: "Posten Norge logistics — phase 4",
    client: "Posten Norge",
    market: "Oslo",
    stage: "unstaffed",
    startDate: "2026-09-15",
    duration: "8 months",
    harmonyScore: null,
    teamIds: [],
    priority: "low",
    briefType: "Engineering programme",
    daysToStart: 110,
    requiredEnergy: { driver: "essential", energizer: "low", supporter: "medium", analyst: "high" },
  },
];

export const seedPitchRoles: PitchRole[] = [
  {
    id: 1,
    briefId: 12,
    title: "Engineering Lead",
    briefName: "Volvo Cars connected platform — extension",
    market: "Stockholm",
    duration: "12 months",
    startDate: "2026-09-01",
    level: "lead",
    requiredEnergy: "driver",
    skills: ["Engineering management", "Cloud architecture", "Programme delivery"],
    applicantCount: 4,
    closingDate: "2026-06-15",
    creditsOnSelection: 80,
    postedDaysAgo: 3,
  },
  {
    id: 2,
    briefId: 13,
    title: "Senior Data Scientist",
    briefName: "Kesko grocery — demand forecasting",
    market: "Helsinki",
    duration: "5 months",
    startDate: "2026-08-01",
    level: "senior",
    requiredEnergy: "analyst",
    skills: ["Applied ML", "Forecasting", "Time-series"],
    applicantCount: 2,
    closingDate: "2026-06-10",
    creditsOnSelection: 60,
    postedDaysAgo: 5,
  },
  {
    id: 3,
    briefId: 14,
    title: "Senior Product Designer",
    briefName: "IKEA experience platform — UX strand",
    market: "Stockholm",
    duration: "9 months",
    startDate: "2026-08-25",
    level: "senior",
    requiredEnergy: "energizer",
    skills: ["Service design", "Design systems", "Workshop facilitation"],
    applicantCount: 6,
    closingDate: "2026-06-20",
    creditsOnSelection: 60,
    postedDaysAgo: 2,
  },
  {
    id: 4,
    briefId: 15,
    title: "Senior Backend Engineer",
    briefName: "Posten Norge logistics — phase 4",
    market: "Oslo",
    duration: "8 months",
    startDate: "2026-09-15",
    level: "senior",
    requiredEnergy: "analyst",
    skills: ["Go", "Event-driven systems", "API security"],
    applicantCount: 1,
    closingDate: "2026-07-01",
    creditsOnSelection: 60,
    postedDaysAgo: 1,
  },
  {
    id: 5,
    briefId: 9,
    title: "UX Lead",
    briefName: "Telia self-service v2",
    market: "Stockholm",
    duration: "8 months",
    startDate: "2026-09-01",
    level: "lead",
    requiredEnergy: "energizer",
    skills: ["Product design", "UX leadership", "Prototyping"],
    applicantCount: 3,
    closingDate: "2026-06-25",
    creditsOnSelection: 80,
    postedDaysAgo: 4,
  },
  {
    id: 6,
    briefId: 7,
    title: "Delivery Lead",
    briefName: "DSB digital experience platform",
    market: "Copenhagen",
    duration: "10 months",
    startDate: "2026-08-01",
    level: "lead",
    requiredEnergy: "supporter",
    skills: ["Programme management", "Agile delivery", "Client governance"],
    applicantCount: 2,
    closingDate: "2026-06-30",
    creditsOnSelection: 80,
    postedDaysAgo: 6,
  },
  {
    id: 7,
    briefId: 8,
    title: "Pitch Director",
    briefName: "Nordea wealth portal — discovery",
    market: "Stockholm",
    duration: "2 months",
    startDate: "2026-07-15",
    level: "lead",
    requiredEnergy: "driver",
    skills: ["Pitch leadership", "C-suite facilitation", "Storytelling"],
    applicantCount: 5,
    closingDate: "2026-06-05",
    creditsOnSelection: 100,
    postedDaysAgo: 1,
  },
  {
    id: 8,
    briefId: 6,
    title: "Strategy Consultant",
    briefName: "Equinor innovation lab — strand 2",
    market: "Oslo",
    duration: "3 months",
    startDate: "2026-07-01",
    level: "mid",
    requiredEnergy: "energizer",
    skills: ["Innovation strategy", "Workshop facilitation"],
    applicantCount: 2,
    closingDate: "2026-06-20",
    creditsOnSelection: 40,
    postedDaysAgo: 7,
  },
];
